---

- name: start graylog
  service: 
    name: graylog-server
    state: started

- name: stop graylog
  service: 
    name: graylog-server
    state: stopped

- name: restart graylog
  service: 
    name: graylog-server
    state: restarted

    
- name: start mongod
  service: 
    name: mongod
    state: started

- name: stop mongod
  service: 
    name: mongod
    state: stopped

- name: restart mongod
  service: 
    name: mongod
    state: restarted

...