---
# Add all dependent roles, that should be executed before
# the content of this role. If this is an appliance
# there should always be atleast these 3 includes

# Change needed roles here
- name: download dependencies from galaxy
  shell: ansible-galaxy install {{ item }}
  args:
    creates: "{{ role_path }}/../{{ item }}"
  with_items:
  - uniqconsulting.os_basic
  - uniqconsulting.open_vm_tools
  - uniqconsulting.firewall
  - uniqconsulting.nginx
  - uniqconsulting.elasticsearch
  - uniqconsulting.mongodb
  - uniqconsulting.graylog

- name: uniqconsulting.os_basic
  include_role:
    name: uniqconsulting.os_basic
  vars:
    osbasic_selinux: true
    osbasic_selinux_policy: disabled
    osbasic_os_update: true
    osbasic_package_cleanup: true
    osbasic_package_upgrade: all
    osbasic_epel: true
    osbasic_syslog: true
    osbasic_syslog_remote_host: '@127.0.0.1:514'

- name: uniqconsulting.open_vm_tools
  include_role:
    name: uniqconsulting.open_vm_tools
  when: install_openvmtools
      
- name: uniqconsulting.firewall
  include_role:
    name: uniqconsulting.firewall
  vars:
    firewall_open_ports: "{{ uniqlog_role_ports + additional_open_ports }}"
    firewall_local_port_forwarding: "{{ uniqlog_firewall_port_forwards }}"
    
- name: uniqconsulting.elasticsearch
  include_role:
    name: uniqconsulting.elasticsearch
  vars:
    elasticsearch_cluster_name: "{{ uniqlog_cluster_name }}"

- name: uniqconsulting.mongodb
  include_role:
    name: uniqconsulting.mongodb

- name: uniqconsulting.graylog
  include_role:
    name: uniqconsulting.graylog
  vars:
    graylog_root_timezone: "Europe/Zurich"
    graylog_allow_highlighting: true
    graylog_dashboard_widget_default_cache_time: 60s
    graylog_cluster_name: "{{ uniqlog_cluster_name }}"

- name: uniqconsulting.nginx
  include_role:
    name: uniqconsulting.nginx
  vars:
    nginx_vhosts:
    - default: yes
      type: proxy
      server_name: "{{ [graylog_hostname] + uniqlog_default_alias }}"
      locations:
      - path: /
        pass: http://127.0.0.1:9000
        custom_options:
        - "proxy_set_header X-Graylog-Server-URL https://$server_name/"

...